<?php

return [
    // [
    //     'title' =>  'Dashboard',
    //     'menu_name' => 'apps',
    //     'create' => false,
    //     'view' => false,
    //     'edit' => false,
    //     'delete' => false,
    // ],
    [
        'title' =>  'User Management',
        'menu_name' => 'user-manage',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],    
    [
        'title' =>  'Brta Status',
        'menu_name' => 'brta-status',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    
    [
        'title' =>  'Brta Booking status',
        'menu_name' => 'brta-booking-status',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  'Operator Management',
        'menu_name' => 'operator-management',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  ' ↳ All Operator',
        'menu_name' => 'all-operator',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  ' ↳ Brta Operator',
        'menu_name' => 'brta-operator',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  ' ↳ Passport Operator',
        'menu_name' => 'passport-operator',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  'Role Management',
        'menu_name' => 'role-management',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  ' ↳ Manage Role',
        'menu_name' => 'manage-role',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  ' ↳ Create-role',
        'menu_name' => 'create-role',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  'Passport Management',
        'menu_name' => 'passport-management',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  ' ↳ All Passport',
        'menu_name' => 'all-passport',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    
];
