<?php

return [
    // [
    //     'title' =>  'Dashboard',
    //     'menu_name' => 'apps',
    //     'create' => false,
    //     'view' => false,
    //     'edit' => false,
    //     'delete' => false,
    // ],
    [
        'title' =>  'User Management',
        'menu_name' => 'user-manage',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],    
    [
        'title' =>  'Brta Status',
        'menu_name' => 'brta-status',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    
    [
        'title' =>  'Brta Booking status',
        'menu_name' => 'brta-booking-status',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  'Brta Booking Report',
        'menu_name' => 'booking-report',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],


    [
        'title' =>  'Operator Management',
        'menu_name' => 'operator-management',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  ' ↳ All Operator',
        'menu_name' => 'all-operator',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  ' ↳ Brta Operator',
        'menu_name' => 'brta-operator',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  ' ↳ Passport Operator',
        'menu_name' => 'passport-operator',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  'Role Management',
        'menu_name' => 'role-management',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  ' ↳ Manage Role',
        'menu_name' => 'manage-role',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  ' ↳ Create-role',
        'menu_name' => 'create-role',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  'Passport Management',
        'menu_name' => 'passport-management',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  ' ↳ All Passport',
        'menu_name' => 'all-passport',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],

    [
        'title' =>  'e-passport received',
        'menu_name' => 'e-passport-received',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  ' ↳ Manage',
        'menu_name' => 'manage',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  ' ↳ Create',
        'menu_name' => 'create',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],

    // Dashboard permission

    [
        'title' =>  'Dashbord status',
        'menu_name' => 'dashboard-licence-status',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],

    [
        'title' =>  'Licence Received',
        'menu_name' => 'dashboard-licence-received',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  'Licence Processed',
        'menu_name' => 'dashboard-licence-processed',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  'Licence Status',
        'menu_name' => 'dashboard-brta-status',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  'Dashboard e-Passpoet',
        'menu_name' => 'dashboard-passport-status',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  'e-Passport Processed',
        'menu_name' => 'dashboard-passport-process',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],
    [
        'title' =>  'e-Passport Status',
        'menu_name' => 'dashboard-passport-status',
        'create' => false,
        'view' => false,
        'edit' => false,
        'delete' => false,
    ],


    
];
